### ISSUE TITLE
Our bob.nightlies are failing because of this package

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.db.msu_mfsd_mod#2]
Hey, our nightlies builds are not passing because of this package.

Check it out.
https://gitlab.idiap.ch/biometric/bob.nightlies

Basically this assertion is not working.
```
      dbfolder = 'bob/db/msu_mfsd_mod/test_images/'  #simulated db repo. containing only the 2 videos used in this test.
      self.assertTrue(os.path.isdir(dbfolder))
```
This assertion may work when the "main" package `bob.db.msu_mfsd_mod`.
However, since this package is a sub-module on nightlies this relatively path is not valid.

I suggest you to use pkg_resources to discover this package (it is more consistent).
For instance you can do something like this.

```
      import pkg_resources
      dbfolder = pkg_resources.resource_filename('bob.db.msu_mfsd_mod','test_images')
     self.assertTrue(os.path.isdir(dbfolder))
```

**Comment by anjos** [comment]
Instead, please use this construction:

```python
dbfolder = pkg_resources.resource_filename(__name__ , 'test_images')
```

Don't hard-code the package name. It makes it more portable and re-usable.

**Comment by skbidiap** [comment]
Thanks for the tips. I have just uploaded the corrected code.

**Comment by tiagofrepereira2012** [comment]
Ok thanks, I will update the nightlies

**Comment by tiagofrepereira2012** [comment]
It is failing again, but for another reason.
So, I will close this one.
Thanks for the fix
